@startuml algoThief
class Juego {
- DatoDeCiudades
- DatosDeLadrones

- IniciarMenu()
- GenerarPartida()

}

class Partida {
' - jugador: Jugador
' - ladron: Ladron
    + GenerarNivel()
}

class Nivel {
- ciudades: Ciudad
- ciudadActual: Ciudad

+ EntrarAEdificio(edif: Edificio)
}

class ManipuladorDeEventos {
+ EscucharEvento(nivel: Nivel)
}

class Jugador {
    - tiempo
    + SumarHoras(horas: int)
}

class Ciudad {
    + Recibir(jugador: Jugador)
    + MostrarPista(): Pista
}

interface Cargo{}
class Novato{}
class Detective{}
class Investigador{}
class Sargento{}

class Pista{}

class Aeropuerto{}
class Puerto{}
class Palacio{}
class Bolsa{}
class Banco{}
class Museo{}

class Ladron{}
class DatosLadron{}
class Sexo{}

interface ObjetoRobado{}
class Comun{}
class Valioso{}
class MuyValioso{}

Jugador --> Cargo

Cargo <|.. Novato
Cargo <|.. Detective
Cargo <|.. Investigador
Cargo <|.. Sargento

Ciudad <|-- Aeropuerto
Ciudad <|-- Puerto
Ciudad <|-- Biblioteca
Ciudad <|-- Palacio
Ciudad <|-- Bolsa
Ciudad <|-- Banco
Ciudad <|-- Museo

Ladron --> DatosLadron
DatosLadron --> Sexo
DatosLadron --> Hobby
DatosLadron --> Cabello
DatosLadron --> Seña
DatosLadron --> Vehiculo

ObjetoRobado <|.. Comun
ObjetoRobado <|.. Valioso
ObjetoRobado <|.. MuyValioso

Juego --> Partida

Partida --> ManipuladorDeEventos
Partida --> Jugador
Partida --> Nivel

Nivel --> Ciudad
Nivel --> Ladron
Nivel <. ManipuladorDeEventos


Jugador <. Nivel
Jugador <. Ciudad

Ladron --> ObjetoRobado

Ciudad -->Pista

@enduml