@startuml algoThief
class Juego {
- DatoDeCiudades
- DatosDeLadrones

- IniciarMenu()
- GenerarPartida()

}

class Partida {
' - jugador: Jugador
' - ladron: Ladron
    + GenerarNivel()
}

class Mapa {
    - mapeo_aux: Map<String,Ciudad>
    + viajar(Jugador jugador,Ciudad ciudadPartida, String ciudadLLlegada, Tiempo tiempo)
    + obtenerCiudad(String ciudad)
    + obtenerCiudad(String ciudad)
    + cargarArchivo()
}

class Interpol {
    - ladronBuscado: String
    - listaLadrones: List<Ladron>
    + buscarLadrones()
}

class Nivel {
- ciudades: Ciudad
- ciudadActual: Ciudad

+ EntrarAEdificio(edif: Edificio)
}

class Tiempo {
    - horas: int
    - horasFin: int
    - dia: int
    - diaFin: int
}

class CreadorDeNiveles {
    - max: int
    - min: int
    + crearNivel()
    + cargarCiudadesNivel()
    + cargarArchivo()
    + cargarLadron()
    + cargarObjetoRobado()
}

class ManipuladorDeEventos {
+ EscucharEvento(nivel: Nivel)
}

class Jugador {
    - tiempo
    + SumarHoras(horas: int)
}

class Ciudad {
    + Recibir(jugador: Jugador)
    + MostrarPista(): Pista
}

class OrdenDeArresto{
- nombreLadronDeOrden: String
}



class Edificio {
    - pista: Pista
}

interface Cargo{}
class Novato{}
class Detective{}
class Investigador{}
class Sargento{}

class Pista{}

class Aeropuerto{}
class Puerto{}
class Palacio{}
class Bolsa{}
class Banco{}
class Museo{}

class Ladron{}
class DatosLadron{}



interface ObjetoRobado{}
class Comun{}
class Valioso{}
class MuyValioso{}

class Tiempo {
    - horas
    - horasFin
    sumarHoras()
}

Jugador --> Cargo

Cargo <|.. Novato
Cargo <|.. Detective
Cargo <|.. Investigador
Cargo <|.. Sargento

Ciudad --> "3" Edificio
Edificio <|-- Aeropuerto
Edificio <|-- Puerto
Edificio <|-- Biblioteca
Edificio <|-- Palacio
Edificio <|-- Bolsa
Edificio <|-- Banco
Edificio <|-- Museo

Ladron --> DatosLadron

ObjetoRobado <|.. Comun
ObjetoRobado <|.. Valioso
ObjetoRobado <|.. MuyValioso

Juego --> Partida

Partida --> ManipuladorDeEventos
Partida --> Jugador
Partida --> Nivel
Partida --> CreadorDeNiveles

Nivel --> Ciudad
Nivel --> Ladron
Nivel <. ManipuladorDeEventos


CreadorDeNiveles .left> Nivel
Jugador <. Nivel
Jugador <. Ciudad

Ladron --> ObjetoRobado


@enduml