@startuml
'https://plantuml.com/sequence-diagram

participant "partida:Partida" as P
participant ":ManipuladorDeEventos" as ME
participant "nivel:Nivel" as N
participant "jugador:Jugador" as J
participant "tiempo:Tiempo" as T

P -> ME: EscucharEvento(partida)
ME -> N: RecibirChuchillada()
N -> J: RecibirChuchillada(tiempo)
J -> T: SumarHoras(2)


@enduml