@startuml
'https://plantuml.com/sequence-diagram

participant ":Juego" as J
participant ":ManipuladorDeEventos" as ME
participant "partida:Partida" as P
participant "banco:Banco" as B
participant "jugador:Jugador" as JG

J -> ME: EscucharEvento(partida)
ME -> P: EntrarEnBanco()
P -> B: Recibir(jugador)
B -> JG: SumarHoras(1)

P -> B: MostrarPista()
P <-- B: pista
ME <-- P: pista

@enduml